---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mon-prometheus-data
  namespace: ers-prod
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com 
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 25Gi
  storageClassName: ocs-external-storagecluster-cephfs 
