---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-pvc-data 
  namespace: ers-prod
  annotations:
#    volume.beta.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com 
    volume.beta.kubernetes.io/storage-provisioner: nfs.storage-class/nfs 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-storage-class
  #storageClassName: ocs-external-storagecluster-cephfs 
---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: gp-logstash 
  name: gp-logstash-9045 
spec:
  ports:
    - name: tcp-gp-logstash-9045
      port: 9045
      protocol: TCP
      targetPort: 9045
  selector:
    app: gp-logstash
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: gp-logstash-txlog 
  name: gp-logstash-txlog
spec:
  ports:
    - name: tcp-gp-logstash-9030
      port: 9030
      protocol: TCP
      targetPort: 9030
  selector:
    app: gp-logstash-txlog 
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: gp-logstash-others 
  name: gp-logstash-others
spec:
  ports:
    - name: tcp-gp-logstash-9030
      port: 9030
      protocol: TCP
      targetPort: 9030
    - name: tcp-gp-logstash-9031
      port: 9031
      protocol: TCP
      targetPort: 9031
    - name: tcp-gp-logstash-9032
      port: 9032
      protocol: TCP
      targetPort: 9032
    - name: tcp-gp-logstash-9033
      port: 9033
      protocol: TCP
      targetPort: 9033
  selector:
    app: gp-logstash-others 
  type: ClusterIP
  
