apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gp-logstash-txlog
  labels:
    app: gp-logstash-txlog
  namespace: ers-prod
spec:
  podManagementPolicy: Parallel
  replicas: 1
  serviceName: gp-logstash-txlog
#  strategy:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 1
#       maxSurge: 50%
  selector:
    matchLabels:
      app: gp-logstash-txlog
  template:
    metadata:
      labels:
        app: gp-logstash-txlog
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"            
      containers:
        - image: sdsdockerhub/logstash-jdbc-v2:8.1.2 #PROD is having logstash-jdbc:8.1.2. We have build with tagging logstash-jdbc-v1:8.1.2 during internal setup
          command: ['logstash','-f','/usr/share/logstash/custom/pipeline']
#        - image: sdsdockerhub/logstash-jdbc:8.1.2
          imagePullPolicy: Always
          name: gp-logstash-txlog
#          resources:
#            limits:
#              cpu: "3"
#              memory: 10Gi
#            requests:
#              cpu: "2"
#              memory: 8Gi
          env:
          - name: TZ
            value: "Asia/Dhaka"
          - name: HOSTNAME_COMMAND
            valueFrom:
              fieldRef: {fieldPath: metadata.name}
          ports:
          - containerPort: 9045
          - containerPort: 9030
          readinessProbe:
            tcpSocket:
              port: 9045
            initialDelaySeconds: 40
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9045
            initialDelaySeconds: 40
            periodSeconds: 5
          volumeMounts:
          - name: logstash-log
            mountPath: /var/seamless/log/logstash/ 
          - name: logstash-config
            mountPath: /usr/share/logstash/config 
          - name: logstash-pipeline
            mountPath: /usr/share/logstash/custom/pipeline 
          - name: logstash-cert
            mountPath: /usr/share/logstash/custom/certs 
            readOnly: true
#         - mountPath: /usr/share/logstash/log4j/pipeline/log4j2.properties
#           name: logstash-nginx-log4j
#           subPath: log4j2.properties            
          - mountPath: /usr/share/zoneinfo/Asia/Dhaka
            name: tz-dhaka
            subPath: Dhaka
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka
        - name: logstash-log
          persistentVolumeClaim:
            claimName: logstash-pvc-data
        - name: logstash-config
          configMap:
            name: logstash-config-txlog
        - name: logstash-pipeline 
          configMap:
            name: logstash-pipeline-txlog
#       - name: logstash-log4j
#         configMap:
#           name: logstash-log4j            
        - name: logstash-cert 
          secret:
            secretName: elastic-search-secret
            optional: true
      imagePullSecrets:
        - name: private-repo
