apiVersion: batch/v1
kind: Job
metadata:
  name: c2s-rc-basic-warmup
  namespace: ers-prod
  app: c2s-rc-basic
spec:
  template:
    spec:
      containers:
      - name: seamless-one-perf
        image: sdsdockerhub/seamless-one-performance:GP-PROD-DATA7
        env:
          - name: CLASS
            value: "simulations.GP.C2SPromoRCExGtSimulation"
          - name: HOST
            value: "nginx-service:18080"
          - name: USERS
            value: "9000"
          - name: TIME
            value: "180"            
          - name: LOGIN
            value: "test_iris"
          - name: PASSWORD
            value: "25de0ca33253864357b8dd07805c26a1"
          - name: REQUEST_GATEWAY_CODE
            value: "IRIS"
          - name: REQUEST_GATEWAY_TYPE
            value: "EXTGW"
          - name: SERVICE_PORT
            value: ""
          - name: SOURCE_TYPE
            value: ""            
          - name: PROTOCOL
            value: "http://"
          - name: AUTH
            value: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXlsb2FkIjoiMkpNUWl2TlFYM0lhcVd3OGg0WHVEa205UWwzM2FZZEFPZkNCbkFINDc0T1I1U1hEWTR1eW95NVl4a2UxR1dnNGJLU0xJNFU2aDFRTk5VRkpSbEdZN0lUdVVLOEZvbE5nakxUT0pUY2RoenlmL1RwbzlBL1JHN1ZLV29nY1h5eFVTclNuUXBubXZpNERnZDE0WSsxVmpzNTYrVGEvMmU1L2RkV1BZd3J4YXlOeDExVlcvc1k0dDl1NFRnTXlSQUR2dlRraEkxMXRIUXV6N2FVM0NVVUluYTErdG1XZ0xwVXpJZW93MENFbmNxN3R2TkEvQ3czMmZLYytNdW5zTlRPdjFGVEtRQ3RkVEYzVFo1R3Q4L3hqZUN5Q256aUNMS2VhIiwiaXNzIjoiRVJTMzYwIiwiZXhwIjoxNjU3MTUwMzM5LCJpYXQiOjE2NTcxMjAzMzl9.SrT7YUZ2CnduI4X3GzvbINka1KU6ESNaLqQpI20XCok"
      restartPolicy: OnFailure
      volumeMounts:
        - mountPath: /results
          name: ers-config-path
    volumes:
      - name: ers-config-path
        emptyDir: {}
            
