apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-standard-link-live
  namespace: ers-prod
  labels:
    app: ers-standard-link
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: ers-standard-link
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.72.46/32,10.18.72.42/32,10.18.72.45/32
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        sidecar.istio.io/inject: "true"
      labels:
        app: ers-standard-link
        version: v1
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      hostAliases:
      - ip: "10.12.121.59"
        hostnames:
        - "snd.apps.prodesbocp311.grameenphone.com"
      - ip: "10.12.121.58"
        hostnames:
        - "prod-ccps.grameenphone.com"          
      initContainers:
        - name: copy-configs
          image: sdsdockerhub/ubuntu:latest
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef: {fieldPath: metadata.name}          
        #  resources:
        #    limits:
        #      cpu: '200m'
        #      memory: 200Mi
        #    requests:
        #      cpu: '100m'
        #      memory: 100Mi
          command: ["bash","-c"]
          args: ["cd /opt/seamless/conf/standard-link && tar xfz conf.tar.gz --no-overwrite-dir && export NAME=$(echo ${POD_NAME}| rev |cut -d'-' -f1 | rev ) && sed -i \"s+/var/seamless/log/standard-link+/var/seamless/log/standard-link/${NAME}+g\" /opt/seamless/conf/standard-link/log4j2.xml "  ]
          volumeMounts:
            - mountPath: /opt/seamless/conf/standard-link
              name: ers-empty-dir
            - mountPath: /opt/seamless/conf/standard-link/conf.tar.gz
              name: vol-conf
              subPath: conf.tar.gz
      containers:
      - name: ers-standard-link
        image: sdsdockerhub/ers-standard-link:feature-GPB-1116-3
        #image: sdsdockerhub/ers-standard-link:feature-GPB-1081-12
        imagePullPolicy: IfNotPresent
        #resources:
        #  limits:
        #    cpu: '3'
        #    memory: 200Mi
        #  requests:
        #    cpu: 2
        #    memory: 1200Mi
        readinessProbe:
          tcpSocket:
            port: 8098
          initialDelaySeconds: 60
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8098
          initialDelaySeconds: 60
          periodSeconds: 10
        env:
        #- name: JAVA_TOOL_OPTIONS
        #  value: "-Xms200M -Xmx18000M -XX:+UseG1GC  -XX:InitiatingHeapOccupancyPercent=70 -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=8"
        - name: DEFAULT_TIME_ZONE
          value: "Asia/Dhaka"
        - name: TZ
          value: "Asia/Dhaka"
        ports:
          - containerPort: 8098
#         - containerPort: 48077
        #dnsPolicy: Default
        volumeMounts:
          - mountPath: /opt/seamless/conf
            name: vol-common-conf
          - mountPath: /opt/seamless/conf/standard-link
            name: ers-empty-dir
          - mountPath: /var/seamless/log/standard-link
            name: vol-log
          - mountPath: /usr/share/zoneinfo/Asia/Dhaka
            name: tz-dhaka
            subPath: Dhaka
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: ers-standard-link-config
        - name: vol-log
          persistentVolumeClaim:
            claimName: ers-standard-link-log
        - name: ers-empty-dir
          emptyDir: {}
      imagePullSecrets:
        - name: private-repo
