apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-ims-bridge
  namespace: ers-prod
  labels:
    app: ims-bridge
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: ims-bridge
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.72.46/32,10.18.72.42/32,10.18.72.45/32
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        sidecar.istio.io/inject: "true"
      labels:
        app: ims-bridge
        version: v1
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      initContainers:
        - name: copy-configs
          image: sdsdockerhub/ubuntu:latest
          env:
          - name: POD_NAME 
            valueFrom:
              fieldRef: {fieldPath: metadata.name}
          #resources:
          #  limits:
          #    cpu: '200m'
          #    memory: 200Mi
          #  requests:
          #    cpu: '100m'
          #    memory: 100Mi
          command: ['bash','/scripts/copy-ims-scripts']
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /ers-common-config
              name: vol-common-conf
            - mountPath: /ims-config
              name: vol-conf
            - mountPath: /scripts
              name: copy-ims-scripts    
      containers:
        - name: ers-ims-bridge
          image: sdsdockerhub/ers-ims-bridge:bugfix-security-fixes-15
          #image: sdsdockerhub/ers-ims-bridge:1.14.2
          imagePullPolicy: IfNotPresent
          #resources:
          #  limits:
          #    cpu: '3000m'
          #    memory: 200Mi
          #  requests:
          #    cpu: '1000m'
          #    memory: 200Mi          
          env:
         # - name: JAVA_TOOL_OPTIONS
         #   value: "-Xms200M -Xmx200M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=3"
          - name: DEFAULT_TIME_ZONE
            value: "Asia/Dhaka" 
          - name: TZ
            value: "Asia/Dhaka"
          readinessProbe:
            tcpSocket:
              port: 8919
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8919
            initialDelaySeconds: 30
            periodSeconds: 20
          ports:
            - containerPort: 8919
          #dnsPolicy: Default  
          volumeMounts:
            - mountPath: /var/seamless/log/ims-bridge
              name: vol-log
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /usr/share/zoneinfo/Asia/Dhaka
              name: tz-dhaka
              subPath: Dhaka        
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka              
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: ims-bridge-config
        - name: vol-log
          persistentVolumeClaim:
            claimName: ims-bridge-log
        - name: copy-ims-scripts
          configMap:
            name: copy-ims-scripts            
        - name: ers-config-path
          emptyDir: {}        
      imagePullSecrets:
        - name: private-repo                
