---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-redis-exporter
  namespace: ers-prod
  labels:
    component: redis-exporter
    role: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis-exporter
      role: redis-exporter
  template:
    metadata:
      labels:
        component: redis-exporter
        role: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        imagePullPolicy: IfNotPresent
        image: sdsdockerhub/redis-exporter:v1
        command: ['redis_exporter','-redis.addr','redis://gp-redis-svc.ers-prod.svc.cluster.local:6379']
        ports:
          - containerPort: 9121
            name: redis-scrape
        env:
        - name: TZ
          value: "Asia/Dhaka"
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
          requests:
            memory: 65Mi
            cpu: 100m
        volumeMounts:
          - mountPath: /usr/share/zoneinfo/Asia/Dhaka
            name: tz-dhaka
            subPath: Dhaka
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka
---
apiVersion: v1
kind: Service
metadata:
  name: prod-redis-gw01-monitor 
  namespace: ers-prod
  labels:
    component: redis-exporter
    role: redis-exporter
spec:
  ports:
  - port: 9121
    name: redis-scrape
  selector:
    component: redis-exporter
    role: redis-exporter
