apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-dealer-management-system-no-cache
  namespace: ers-prod
  labels:
    app: dealer-management-system
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: dealer-management-system
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.72.46/32,10.18.72.42/32,10.18.72.45/32
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        sidecar.istio.io/inject: "true"
      labels:
        app: dealer-management-system
        version: v1
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      initContainers:
        - name: copy-configs
          image: sdsdockerhub/ubuntu:latest
          env:
          - name: POD_NAME 
            valueFrom:
              fieldRef: {fieldPath: metadata.name}                
        #  resources:
         #   limits:
         #     cpu: '300m'
         #     memory: 300Mi
         #   requests:
         #     cpu: 100m              
         #     memory: 100Mi            
          command: ['bash','/scripts/copy-dealer-management-configs']
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /ers-common-config
              name: vol-common-conf
            - mountPath: /dealer-management-config
              name: vol-conf
            - mountPath: /dealer-management-template-config
              name: vol-conf-template
            - mountPath: /scripts
              name: copy-dealer-management-configs
      containers:
      - name: ers-dealer-management-system
        image: sdsdockerhub/ers-dealer-management-system:feature-GPB-1117-16
        #image: sdsdockerhub/ers-dealer-management-system:feature-GPB-1117-14
        imagePullPolicy: IfNotPresent
        env:
       # - name: JAVA_TOOL_OPTIONS
       #   value: "-Xms200M -Xmx200M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=2"
        - name: DEFAULT_TIME_ZONE
          value: "Asia/Dhaka" 
        - name: TZ
          value: "Asia/Dhaka"
        #resources:
        #  limits:
        #    cpu: '1'
        #    memory: 200Mi
        #  requests:
        #    cpu: '500m'
        #    memory: 200Mi
        readinessProbe:
          tcpSocket:
            port: 8033
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8033
          initialDelaySeconds: 30
          periodSeconds: 20
        ports:
          - containerPort: 8033
        #dnsPolicy: Default
        volumeMounts:
          - mountPath: /opt/seamless/conf
            name: ers-config-path
          - mountPath: /var/seamless/log/dealer-management-system
            name: vol-log
          - mountPath: /usr/share/zoneinfo/Asia/Dhaka
            name: tz-dhaka
            subPath: Dhaka            
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka              
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: dealer-management-system-config-no-cache 
        - name: vol-conf-template
          configMap:
            name: dealer-management-system-config-templates
        - name: copy-dealer-management-configs
          configMap:
            name: copy-dealer-management-configs
        - name: vol-log
          persistentVolumeClaim:
            claimName: dealer-management-system-log
        - name: ers-config-path
          emptyDir: {}
      imagePullSecrets:
        - name: private-repo
