
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-centos
  name: my-centos
spec:
  containers:
  - image: sdshubdocker/all-utilities:latest
    command: ["sleep"]
    args: ["3600"]
    name: my-centos
    resources:
      limits:
        cpu: "200m"
        memory: 200Mi
      requests:
        cpu: "100m"
        memory: 100Mi
  imagePullSecrets:
  - name: private-repo
  dnsPolicy: ClusterFirst
  restartPolicy: Always
