groups:
    - name:  PROD REDIS
      rules:

      - alert: RedisProductionDown
        expr: redis_up == 0 
        for: 1m
        labels:
          severity: critical
          messagecode: RedisProductionDown
          application: Redis
          service: '{{ $labels.instance }}'
          namespace: ers-prod
        annotations:
          summary: Redis Production down (instance {{ $labels.instance }})
          description: "Redis Production instance is down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

 
      - alert: RedisOutOfSystemMemory
        expr: redis_memory_used_bytes / redis_total_system_memory_bytes * 100 > 90
        for: 20m
        labels:
          severity: critical
          messagecode: RedisOutOfSystemMemory
          application: Redis
          service: '{{ $labels.instance }}'                           
          namespace: ers-prod
        annotations:
          summary: Redis out of system memory (instance {{ $labels.instance }})
          description: "Redis is running out of system memory (> 90%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    
      - alert: RedisProdTooManyConnections
        expr: redis_connected_clients{job="redis_exporter_app"} > 2500  
        for: 15m
        labels:
          severity: warning
          messagecode: RedisProdTooManyConnections
          application: Redis
          service: '{{ $labels.instance }}'                            
          namespace: ers-prod
        annotations:
          summary: Redis Production too many connections (instance {{ $labels.instance }})
          description: "Redis Production instance has too many connections\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"



