apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-group-management
  namespace: ers-prod
  labels:
    app: ers-group-management
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: ers-group-management
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.68.82/32
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
#        sidecar.istio.io/inject: "true"
      labels:
        app: ers-group-management
        version: v1
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      initContainers:
        - name: copy-configs
          image: sdsdockerhub/ubuntu:latest
          env:
          - name: HOSTNAME_COMMAND
            valueFrom:
              fieldRef: {fieldPath: metadata.name}
          #resources:
          #  limits:
          #    cpu: '200m'
          #    memory: 200Mi
          #  requests:
          #    cpu: 100m              
          #    memory: 100Mi                               
          command: ['bash','/scripts/copy-group-management-configs']
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /ers-common-config
              name: vol-common-conf
            - mountPath: /group-management-config
              name: vol-conf
            - mountPath: /group-management-templates-config
              name: vol-templates
            - mountPath: /scripts
              name: copy-group-management-configs
      containers:
      - name: ers-group-management
        image: sdsdockerhub/group-management-system:feature-UPI-1500-4
        #image: sdsdockerhub/group-management-system:1.19.0
        imagePullPolicy: IfNotPresent 
        #resources:
        #  limits:
        #    cpu: '1000m'
        #    memory: 200Mi
        #  requests:
        #    cpu: '500m'              
        #    memory: 500Mi                     
        env:
        #- name: JAVA_TOOL_OPTIONS
        #  value: "-Xms200M -Xmx200M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=1"
        - name: DEFAULT_TIME_ZONE
          value: "Asia/Dhaka" 
        - name: TZ
          value: "Asia/Dhaka"
        ports:
          - containerPort: 8084 
        #dnsPolicy: Default
        readinessProbe:
          tcpSocket:
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 5  
        livenessProbe:
          tcpSocket:
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 5                   
        volumeMounts:
          - mountPath: /opt/seamless/conf
            name: ers-config-path
          - mountPath: /var/seamless/log/group-management
            name: vol-log                                    
          - mountPath: /usr/share/zoneinfo/Asia/Dhaka
            name: tz-dhaka
            subPath: Dhaka            
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka              
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: group-management-config
        - name: vol-templates
          configMap:
            name: group-management-templates-config
        - name: vol-log
          persistentVolumeClaim:
            claimName: ers-group-management-log
        - name: copy-group-management-configs
          configMap:
            name: copy-group-management-configs
        - name: ers-config-path
          emptyDir: {}
      imagePullSecrets:
        - name: private-repo
