#FROM default-route-openshift-image-registry.apps.pocpbm-nexp.grameenphone.com/openshift/seamless-one-performance:POST-LIVE-LT-V1
FROM sdsdockerhub/seamless-one-performance:GP-LOAD-TEST2-1
COPY c2s_Promo_Ppb_ExGt.csv /opt/seamless/conf/seamless-one-performance/data/GP/.
COPY c2s_Promo_Ppb_ExGt.xml /opt/seamless/conf/seamless-one-performance/body/SLC/.
