apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-object-store-manager
  namespace: ers-prod
  labels:
    app: ers-object-store-manager
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: ers-object-store-manager
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.72.46/32,10.18.72.42/32,10.18.72.45/32
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        sidecar.istio.io/inject: "true"
      labels:
        app: ers-object-store-manager
        version: v1
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      containers:
        - name: ers-object-store-manager
          image: sdsdockerhub/object-store-manager:1.12.0
          #image: sdsdockerhub/object-store-manager:develop-10
          imagePullPolicy: IfNotPresent
#          resources:
#            limits:
#              cpu: '1000m'
#              memory: 200Mi
#            requests:
#              cpu: 500m
#              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
          env:
 #         - name: JAVA_TOOL_OPTIONS
 #           value: "-Xms200M -Xmx200M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=1"
          - name: DEFAULT_TIME_ZONE
            value: "Asia/Dhaka" 
          - name: TZ
            value: "Asia/Dhaka"        
          ports:
            - containerPort: 3000
          #dnsPolicy: Default
          volumeMounts:
            - mountPath: /opt/seamless/conf/object-store-manager
              name: vol-conf
            - mountPath: /opt/seamless/conf/object-store-manager/locales
              name: vol-conf-locales
            - mountPath: /var/seamless/log/object-store-manager
              name: vol-log
            - mountPath: /opt/seamless/conf
              name: vol-common-conf
            - mountPath: /usr/share/zoneinfo/Asia/Dhaka
              name: tz-dhaka
              subPath: Dhaka              
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka              
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: object-store-config
        - name: vol-conf-locales
          configMap:
            name: object-store-config-locales
        - name: vol-log
          persistentVolumeClaim:
            claimName: object-store-log

