apiVersion: v1
kind: ConfigMap
metadata:
  name: gp-filebeat-configmap-account
  namespace: ers-prod
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: filestream
      id: transactionlog
      paths:
        - /var/seamless/log/account-management-service/*/account-management-service-data.dump*
      tags: ["accountlog"]
      fields:
        logtype: "accountlog"
      ignore_older: 24h
      clean_inactive: 8h
      close_inactive: 8h
      exclude_files: ['\.gz$']
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    logging.level: info
    logging.to_files: true
    logging.selectors: [ harvester, input ]
    logging.files:
      rotateeverybytes: 5000000
      path: /usr/share/filebeat/logs
      name: filebeat.log
      keepfiles: 5
    output.logstash:
      hosts: ["gp-logstash-others:9031"]
      loadbalance: true
      bulk_max_size: 1024
      worker: 32
      compression_level: 1
    queue.mem:
      events: 32768
      flush.min_events: 1024
      flush.timeout: 5s
