---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-dir
  namespace: ers-prod
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: nfs.storage-class/nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: nfs-storage-class
---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: gp-minio
  name: gp-minio-service
  namespace: ers-prod
spec:
  ports:
    - name: http-gp-minio-service
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: gp-minio
  type: ClusterIP
