apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-region-management
  namespace: ers-prod
  labels:
    app: ers-region-management
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: ers-region-management
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.72.46/32,10.18.72.42/32,10.18.72.45/32
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        sidecar.istio.io/inject: "true"
      labels:
        app: ers-region-management
        version: v1
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      initContainers:
        - name: copy-configs
          image: sdsdockerhub/ubuntu:latest
          env:
          - name: POD_NAME 
            valueFrom:
              fieldRef: {fieldPath: metadata.name}          
          imagePullPolicy: IfNotPresent
          #resources:
          #  limits:
          #    cpu: '200m'
          #    memory: 200Mi
          #  requests:
          #    cpu: 100m
          #    memory: 100Mi
          command: ['bash','/scripts/copy-region-management-configs']
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /ers-common-config
              name: vol-common-conf
            - mountPath: /region-management-config
              name: vol-conf
            - mountPath: /region-management-templates-config
              name: vol-templates-conf
            - mountPath: /scripts
              name: copy-region-management-configs
      containers:
        - name: ers-region-management
          image: sdsdockerhub/ers-region-management:437-5
          #image: sdsdockerhub/ers-region-management:feature-SE-437-8
          #image: sdsdockerhub/ers-region-management:1.9.4
          imagePullPolicy: IfNotPresent
          #resources:
          #  limits:
          #    cpu: '1000m'
          #    memory: 200Mi
          #  requests:
          #    cpu: 1000m
          #    memory: 200Mi
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
          env:
          #- name: JAVA_TOOL_OPTIONS
          #  value: "-Xms200M -Xmx20000M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=1"
          - name: DEFAULT_TIME_ZONE
            value: "Asia/Dhaka" 
          - name: TZ
            value: "Asia/Dhaka"        
          ports:
            - containerPort: 8000
          #dnsPolicy: Default
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path 
            - mountPath: /var/seamless/log/region-management-core 
              name: vol-log
            - mountPath: /usr/share/zoneinfo/Asia/Dhaka
              name: tz-dhaka
              subPath: Dhaka              
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka              
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: region-management-core-config
        - name: vol-templates-conf 
          configMap:
            name: region-management-core-config-templates
        - name: copy-region-management-configs
          configMap:
            name: copy-region-management-configs
        - name: vol-log
          persistentVolumeClaim:
            claimName: region-management-log
        - name: ers-config-path
          emptyDir: {}
      imagePullSecrets:
        - name: private-repo
