apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-notification-manager
  namespace: ers-prod
  labels:
    app: ers-notification-manager
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:  
      app: ers-notification-manager
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.68.82/32 
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        sidecar.istio.io/inject: "true"
      labels:
        app: ers-notification-manager
        version: v1
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      initContainers:
        - name: copy-configs
          image: sdsdockerhub/ubuntu:latest
          env:
          - name: POD_NAME 
            valueFrom:
              fieldRef: {fieldPath: metadata.name}
         # resources:
         #   limits:
         #     cpu: '200m'
         #     memory: 200Mi
         #   requests:
         #     cpu: '100m'
         #     memory: 100Mi
          command: ['bash','/scripts/copy-notification-manager-scripts']
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /ers-common-config
              name: vol-common-conf
            - mountPath: /notification-manager-config
              name: vol-conf
            - mountPath: /scripts
              name: copy-notification-manager-scripts    
      containers:
        - name: ers-notification-manager
          image: sdsdockerhub/ers-notification-manager:feature-GPB-1081-7
          #image: sdsdockerhub/ers-notification-manager:feature-GPB-1081-6
          #image: sdsdockerhub/ers-notification-manager:feature-GPB-935-7
          imagePullPolicy: IfNotPresent
          env:
          #- name: JAVA_TOOL_OPTIONS
          #  value: "-Xms200M -Xmx200M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=4"
          - name: DEFAULT_TIME_ZONE
            value: "Asia/Dhaka"
          - name: TZ
            value: "Asia/Dhaka"
          #resources:
          #  limits:
          #    cpu: '1500m'
          #    memory: 200Mi
          #  requests:
          #    cpu: '750m'
          #    memory: 200Mi
          readinessProbe:
            tcpSocket:
              port: 8277
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8277
            initialDelaySeconds: 30
            periodSeconds: 20
          ports:
            - containerPort: 8277
          #dnsPolicy: Default
          volumeMounts:
            - mountPath: /var/seamless/log/notification-manager
              name: vol-log
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /usr/share/zoneinfo/Asia/Dhaka
              name: tz-dhaka
              subPath: Dhaka                            
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka              
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: notification-manager-config
        - name: vol-core-conf
          configMap:
            name: core-config
        - name: vol-log
          persistentVolumeClaim:
            claimName: notification-manager-log
        - name: copy-notification-manager-scripts
          configMap:
            name: copy-notification-manager-scripts            
        - name: ers-config-path
          emptyDir: {}   
      imagePullSecrets:
        - name: private-repo                     
