---
apiVersion: v1
kind: Service
metadata:
  name: prod-gw01-node
  namespace: ers-prod
  labels:
    app: prod-gw01-node 
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 9200
---
apiVersion: v1
kind: Endpoints
metadata:
  name: prod-gw01-node 
  namespace: ers-prod
  labels:
    app: prod-gw01-node 
subsets:
  - addresses:
    - ip: 10.18.12.124 
    ports:
    - port: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: prod-gw02-node 
  namespace: ers-prod
  labels:
    app: prod-gw02-node 
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 9200
---
apiVersion: v1
kind: Endpoints
metadata:
  name: prod-gw02-node 
  namespace: ers-prod
  labels:
    app: prod-gw02-node 
subsets:
  - addresses:
    - ip: 10.18.12.122
    ports:
    - port: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: prod-nms01-node 
  namespace: ers-prod
  labels:
    app: prod-nms01-node 
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 9200
---
apiVersion: v1
kind: Endpoints
metadata:
  name: prod-nms01-node 
  namespace: ers-prod
  labels:
    app: prod-nms01-node 
subsets:
  - addresses:
    - ip: 10.18.68.81 
    ports:
    - port: 9200
