apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-access-management-system
  namespace: ers-prod
  labels:
    app: ers-access-management-system
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: ers-access-management-system
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.72.46/32,10.18.72.42/32,10.18.72.45/32
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        sidecar.istio.io/inject: "true"
      labels:
        app: ers-access-management-system
        version: v1
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      initContainers:
        - name: copy-configs
          image: sdsdockerhub/ubuntu:latest
          env:
          - name: POD_NAME 
            valueFrom:
              fieldRef: {fieldPath: metadata.name}                    
          imagePullPolicy: IfNotPresent
          #resources:
          #  limits:
          #    cpu: '200m'
          #    memory: 200Mi
          #  requests:
          #    cpu: 100m              
          #    memory: 100Mi                                         
          command: ['bash','/scripts/copy-access-management-configs']
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /ers-common-config
              name: vol-common-conf
            - mountPath: /access-management-config
              name: vol-conf
            - mountPath: /access-management-templates-config
              name: vol-templates-conf
            - mountPath: /scripts
              name: copy-access-management-configs
      containers:
      - name: ers-access-management-system
        image: sdsdockerhub/access-management-system:feature-GPB-1104-2
        #image: sdsdockerhub/access-management-system:feature-GPB-924-2
        imagePullPolicy: Always
        #resources:
        #  limits:
        #    cpu: '500m'
        #    memory: 200Mi
        #  requests:
        #    cpu: '200m'
        #    memory: 200Mi          
        env:
       # - name: JAVA_TOOL_OPTIONS
       #   value: "-Xms200M -Xmx200M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=1 -Dlogging.config=/opt/seamless/conf/access-management-system/log4j2.xml "
        - name: DEFAULT_TIME_ZONE
          value: "Asia/Dhaka"
        - name: TZ
          value: "Asia/Dhaka"
       #- name: POD_NAME
       #  valueFrom:
       #    fieldRef:
       #      fieldPath: metadata.name
        ports:
          - containerPort: 8374
        readinessProbe:
          tcpSocket:
            port: 8374
          initialDelaySeconds: 40
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8374
          initialDelaySeconds: 40
          periodSeconds: 20            
        #dnsPolicy: Default
        volumeMounts:
          - mountPath: /opt/seamless/conf
            name: ers-config-path
          - mountPath: /var/seamless/log/access-management-system
            name: vol-log
          - mountPath: /usr/share/zoneinfo/Asia/Dhaka 
            name: tz-dhaka 
            subPath: Dhaka
      volumes:
        - name: tz-dhaka 
          configMap:
            name: asia-dhaka-tz-config 
            items:
            - key: Dhaka
              path: Dhaka
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: access-management-config
        - name: vol-templates-conf
          configMap:
            name: access-management-templates-config
        - name: copy-access-management-configs
          configMap:
            name: copy-access-management-configs
        - name: vol-log
          persistentVolumeClaim:
            claimName: access-management-system-log
        - name: ers-config-path
          emptyDir: {}
     #imagePullSecrets:
       #- name: private-repo
