---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebeat-registry-txlog
  namespace: ers-prod
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: nfs.storage-class/nfs 
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage-class
