---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-nginx-pvc-data 
  namespace: ers-prod
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: nfs.storage-class/nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage-class
---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: gp-logstash-nginx 
  name: gp-logstash-nginx-9045 
spec:
  ports:
    - name: tcp-gp-logstash-9045
      port: 9045
      protocol: TCP
      targetPort: 9045
  selector:
    app: gp-logstash-nginx 
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: gp-logstash-nginx
  name: gp-logstash-nginx-9044
spec:
  ports:
    - name: tcp-gp-logstash-9044
      port: 9044
      protocol: TCP
      targetPort: 9044
  selector:
    app: gp-logstash-nginx 
  type: ClusterIP
