apiVersion: apps/v1
kind: Deployment
metadata:
  name: gp-logstash-nginx
  labels:
    app: gp-logstash-nginx
  namespace: ers-prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 20%
       maxUnavailable: 20%  
  selector:
    matchLabels:
      app: gp-logstash-nginx
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 10m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.68.76/32,10.18.68.90/32,10.18.68.94/32
#        sidecar.istio.io/inject: "true"
      labels:
        app: gp-logstash-nginx
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      containers:
        - image: sdsdockerhub/logstash:8.1.2
          name: gp-logstash
#          resources:
#            limits:
#              cpu: "2"
#              memory: 10Gi
#            requests:
#              cpu: "1"
#              memory: 8Gi
          readinessProbe:
            tcpSocket:
              port: 9044
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9044
            initialDelaySeconds: 30
            periodSeconds: 20
          env:
          - name: TZ
            value: "Asia/Dhaka"
          ports:
          - containerPort: 9044
          - containerPort: 9045
          volumeMounts:
          - name: logstash-log
            mountPath: /var/seamless/log/logstash/ 
          - name: logstash-config
            mountPath: /usr/share/logstash/config 
          - name: logstash-pipeline
            mountPath: /usr/share/logstash/custom/pipeline 
          - name: logstash-cert
            mountPath: /usr/share/logstash/custom/certs 
            readOnly: true
#         - mountPath: /usr/share/logstash/log4j/pipeline/log4j2.properties 
#           name: logstash-nginx-log4j 
#           subPath: log4j2.properties
          - mountPath: /usr/share/zoneinfo/Asia/Dhaka
            name: tz-dhaka
            subPath: Dhaka
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka
        - name: logstash-log
          persistentVolumeClaim:
            claimName: logstash-nginx-pvc-data
        - name: logstash-config
          configMap:
            name: logstash-config-nginx
        - name: logstash-pipeline 
          configMap:
            name: logstash-pipeline-nginx
#       - name: logstash-nginx-log4j 
#         configMap:
#           name: logstash-nginx-log4j 
        - name: logstash-cert 
          secret:
            secretName: elastic-search-secret-nginx
            optional: true
      imagePullSecrets:
        - name: private-repo
