FROM default-route-openshift-image-registry.apps.pocpbm-nexp.grameenphone.com/openshift/seamless-one-performance:GP-PROD-DATA7
COPY c2s_Skitto_ExGt.csv /opt/seamless/conf/seamless-one-performance/data/GP/.
COPY c2s_Skitto_ExGt.xml /opt/seamless/conf/seamless-one-performance/body/SLC/.
