apiVersion: batch/v1
kind: CronJob
metadata:
  name: gp-rsync-non-monetary-app-log
spec:
  schedule: "*/2 * * * *"              #CRON TIME IS BASED ON GMT
 #schedule: "25 */8 * * *"              #CRON TIME IS BASED ON GMT
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ers-prod-app-sa
          securityContext:
            fsGroupChangePolicy: "OnRootMismatch"
            seLinuxOptions:
              type: "spc_t"                
          containers:
          - name: gp-rsync-non-monetary-app-log 
#           image: default-route-openshift-image-registry.apps.pocpbm-nexp.grameenphone.com/openshift/rsync-log:v5   #current logs were cleaned and removed
            #image: default-route-openshift-image-registry.apps.pocpbm-nexp.grameenphone.com/openshift/rsync-log:v6   #current logs are cleaned
            image: sdsdockerhub/rsync-log:v7
            imagePullPolicy: Always
          #  resources:
          #    limits:
          #      cpu: '200m'
          #      memory: 200Mi
          #    requests:
          #      cpu: 100m
          #      memory: 100Mi            
            env:
            - name: SERVER
              value: "10.10.0.115"
            - name: PORT
              value: "22"
            - name: USER
              value: "admin"
            - name: REMOTE_LOG_PATH
              value: "/app/APP_LOGS/NONTXN"
            - name: REMOTE_DUMP_PATH
              value: "/app/APP_DUMPS/NONTXN"
            - name: TZ
              value: "Asia/Dhaka"  
            - name: MTIME
              value: "720"  
            command:
            - /bin/sh
            - -c
            - /others/sync-log.sh
            volumeMounts:
            - name: id-rsa
              mountPath: /home/admin/.ssh/id_rsa
              readOnly: true
              subPath: id_rsa
            - name: id-rsa-pub
              mountPath: /home/admin/.ssh/id_rsa.pub
              readOnly: true
              subPath: id_rsa.pub
            - name: known-host
              mountPath: /home/admin/.ssh/known_hosts
              readOnly: true
              subPath: known_hosts
            - mountPath: /usr/share/zoneinfo/Asia/Dhaka
              name: tz-dhaka
              subPath: Dhaka               
            - name: vol-alertapp
              mountPath: /var/seamless/log/alertapp
            - name: vol-autotransfer
              mountPath: /var/seamless/log/autotransfer-manager
            - name: vol-batch
              mountPath: /var/seamless/log/batch-scheduling
            - name: vol-biagg1
              mountPath: /var/seamless/log/bi-aggregator1
            - name: vol-biagg2
              mountPath: /var/seamless/log/bi-aggregator2
            - name: vol-biagg3
              mountPath: /var/seamless/log/bi-aggregator3
            - name: vol-biengine
              mountPath: /var/seamless/log/bi-engine
            - name: vol-bitdr
              mountPath: /var/seamless/log/bi-tdr-exporter
            - name: vol-bimail
              mountPath: /var/seamless/log/bi-mail-engine
            - name: vol-commagg
              mountPath: /var/seamless/log/commission-aggregator
            - name: vol-commengine
              mountPath: /var/seamless/log/commission-engine
            - name: vol-osm
              mountPath: /var/seamless/log/object-store-manager
            - name: vol-notificationui
              mountPath: /var/seamless/log/notification-ui
            - name: vol-ldap
              mountPath: /var/seamless/log/ldaplink-core
            - name: vol-imsbridge
              mountPath: /var/seamless/log/ims-bridge
          restartPolicy: OnFailure
          volumes:
          - name: tz-dhaka
            configMap:
              name: asia-dhaka-tz-config
              items:
              - key: Dhaka
                path: Dhaka          
          - name: id-rsa
            configMap:
              name: log-rsync-ssh-cm-id
          - name: id-rsa-pub
            configMap:
              name: log-rsync-ssh-cm-idpub
          - name: known-host
            configMap:
              name: log-rsync-ssh-cm-kh
          - name: vol-alertapp
            persistentVolumeClaim:
              claimName: alert-app-log
          - name: vol-autotransfer
            persistentVolumeClaim:
              claimName: ers-autotransfer-manager-log
          - name: vol-batch
            persistentVolumeClaim:
              claimName: batch-scheduling-log
          - name: vol-biengine
            persistentVolumeClaim:
              claimName: bi-engine-new-log
          - name: vol-biagg1
            persistentVolumeClaim:
              claimName: bi-aggregator-log
          - name: vol-biagg2
            persistentVolumeClaim:
              claimName: bi-aggregator2-log
          - name: vol-biagg3
            persistentVolumeClaim:
              claimName: bi-aggregator3-log
          - name: vol-bitdr
            persistentVolumeClaim:
              claimName: bi-tdr-log
          - name: vol-bimail
            persistentVolumeClaim:
              claimName: ers-bimail-log
          - name: vol-commagg
            persistentVolumeClaim:
              claimName: commission-aggregator-log
          - name: vol-commengine
            persistentVolumeClaim:
              claimName: commission-engine-log
          - name: vol-osm
            persistentVolumeClaim:
              claimName: object-store-log
          - name: vol-notificationui
            persistentVolumeClaim:
              claimName: notification-ui-log
          - name: vol-ldap
            persistentVolumeClaim:
              claimName: ldaplink-log
          - name: vol-imsbridge
            persistentVolumeClaim:
              claimName: ims-bridge-log
