---
apiVersion: v1
kind: Service
metadata:
  name: es-01-monitor
  namespace: ers-prod
  labels:
    app: es-01-monitor 
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 9104
---
apiVersion: v1
kind: Endpoints
metadata:
  name: es-01-monitor 
  namespace: ers-prod
  labels:
    app: es-01-monitor 
subsets:
  - addresses:
    - ip: 10.18.68.76 
    ports:
    - port: 9104
---
apiVersion: v1
kind: Service
metadata:
  name: es-02-monitor 
  namespace: ers-prod
  labels:
    app: es-02-monitor 
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 9104
---
apiVersion: v1
kind: Endpoints
metadata:
  name: es-02-monitor 
  namespace: ers-prod
  labels:
    app: es-02-monitor 
subsets:
  - addresses:
    - ip: 10.18.68.90
    ports:
    - port: 9104
---
apiVersion: v1
kind: Service
metadata:
  name: es-03-monitor 
  namespace: ers-prod
  labels:
    app: es-03-monitor 
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 9104
---
apiVersion: v1
kind: Endpoints
metadata:
  name: es-03-monitor 
  namespace: ers-prod
  labels:
    app: es-03-monitor 
subsets:
  - addresses:
    - ip: 10.18.68.94 
    ports:
    - port: 9104
