apiVersion: batch/v1
kind: CronJob
metadata:
  name: gp-lang-pref-daily
spec:
  schedule: "30 18 * * *" #IN UTC TIME
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ers-prod-app-sa
          securityContext:
            fsGroupChangePolicy: "OnRootMismatch"
            seLinuxOptions:
              type: "spc_t"
          containers:
          - name: gp-lang-pref
            image: default-route-openshift-image-registry.apps.pocpbm-nexp.grameenphone.com/openshift/ers-notification-language-preference:build-2
            imagePullPolicy: Always
            resources:
              limits:
                cpu: '200m'
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 100Mi            
            env:
            - name: NMS_HOST
              value: "ers-notification-manager-service.ers-prod.svc.cluster.local"
            - name: NMS_PORT
              value: "8277"
            - name: RECIPIENT_IDS
              value: "rebonta.deb@seamless.se"
            - name: SENDER_MAIL
              value: "lang-preference@grameenphone.com"
            - name: REMOTE_PATH
              value: "/cdrdata/oracle/ProdEDW/source_data/BTRC_BANGLA_SMS"
            - name: USER
              value: "svc_music_sftp"
            - name: IP
              value: "10.12.121.41"
            - name: PORT
              value: "23025"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lang-pref-sftp-pass
                  key: sftp-pass
                  optional: false  
            - name: TZ
              value: "Asia/Dhaka"
            command:
            - /bin/sh
            - -c
            - /sds-scripts/notification-language-daily.sh
            volumeMounts:
            - name: ssh-config
              mountPath: /.ssh/config
              readOnly: true
              subPath: config
            - name: known-hosts
              mountPath: /.ssh/known_hosts
              readOnly: true
              subPath: known_hosts
            - name: daily-file
              mountPath: /sds-scripts/notification-language-daily.sh
              subPath: notification-language-daily.sh
            - name: log-pvc
              mountPath: /var/seamless/log/notification-language-preference
            - mountPath: /usr/share/zoneinfo/Asia/Dhaka
              name: tz-dhaka
              subPath: Dhaka
          restartPolicy: OnFailure
          volumes:
          - name: tz-dhaka
            configMap:
              name: asia-dhaka-tz-config
              items:
              - key: Dhaka
                path: Dhaka
          - name: ssh-config
            configMap:
              name: lang-pref-ssh-config
          - name: known-hosts
            configMap:
              name: lang-pref-ssh-known-host
          - name: daily-file
            configMap:
              name: lang-pref-daily-script
              defaultMode: 0755              
          - name: log-pvc
            persistentVolumeClaim:
              claimName: language-preference
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gp-lang-pref-weekly
spec:
  schedule: "15 17 * * SUN"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ers-prod-app-sa
          securityContext:
            fsGroupChangePolicy: "OnRootMismatch"
            seLinuxOptions:
              type: "spc_t"
          containers:
          - name: gp-lang-pref
            image: default-route-openshift-image-registry.apps.pocpbm-nexp.grameenphone.com/openshift/ers-notification-language-preference:build-2
            imagePullPolicy: Always
            resources:
              limits:
                cpu: '200m'
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 100Mi            
            env:
            - name: NMS_HOST
              value: "ers-notification-manager-service.ers-prod.svc.cluster.local"
            - name: NMS_PORT
              value: "8277"
            - name: RECIPIENT_IDS
              value: "rebonta.deb@seamless.se"
            - name: SENDER_MAIL
              value: "lang-preference@grameenphone.com"
            - name: REMOTE_PATH
              value: "/cdrdata/oracle/ProdEDW/source_data/BTRC_BANGLA_SMS"
            - name: USER
              value: "svc_music_sftp"
            - name: IP
              value: "10.12.121.41"
            - name: PORT
              value: "23025"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lang-pref-sftp-pass
                  key: sftp-pass
                  optional: false              
            - name: TZ
              value: "Asia/Dhaka"
            command:
            - /bin/sh
            - -c
            - /sds-scripts/notification-language-weekly.sh                    
            volumeMounts:
            - name: ssh-config
              mountPath: /.ssh/config
              readOnly: true
              subPath: config
            - name: known-hosts
              mountPath: /.ssh/known_hosts
              readOnly: true
              subPath: known_hosts
            - name: weekly-file
              mountPath: /sds-scripts/notification-language-weekly.sh
              subPath: notification-language-weekly.sh
            - name: log-pvc
              mountPath: /var/seamless/log/notification-language-preference
            - mountPath: /usr/share/zoneinfo/Asia/Dhaka
              name: tz-dhaka
              subPath: Dhaka
          restartPolicy: OnFailure
          volumes:
          - name: tz-dhaka
            configMap:
              name: asia-dhaka-tz-config
              items:
              - key: Dhaka
                path: Dhaka
          - name: ssh-config
            configMap:
              name: lang-pref-ssh-config
          - name: known-hosts
            configMap:
              name: lang-pref-ssh-known-host
          - name: weekly-file
            configMap:
              name: lang-pref-weekly-script
              defaultMode: 0755
          - name: log-pvc
            persistentVolumeClaim:
              claimName: language-preference
