#!/bin/bash
name=`echo ${POD_NAME} | rev |cut -d'-' -f1 | rev `
mkdir -p /opt/seamless/conf/access-management-system
mkdir -p /opt/seamless/conf/access-management-system/templates

cp /ers-common-config/* /opt/seamless/conf/
cp /access-management-config/* /opt/seamless/conf/access-management-system/
cp /access-management-templates-config/* /opt/seamless/conf/access-management-system/templates/
sed -i "s+/var/seamless/log/access-management-system+/var/seamless/log/access-management-system/${name}+g" /opt/seamless/conf/access-management-system/log4j2.xml
#sed -i "s+=/var/seamless/log/access-management-system/+=/var/seamless/log/access-management-system/${name}/+g" /opt/seamless/conf/access-management-system/log4j.properties