#!/bin/bash
name=`echo ${POD_NAME} | rev |cut -d'-' -f1 | rev `
mkdir -p /opt/seamless/conf/dealer-management-system
mkdir -p /opt/seamless/conf/dealer-management-system/templates

cp /ers-common-config/* /opt/seamless/conf/
cp /dealer-management-config/* /opt/seamless/conf/dealer-management-system/
cp /dealer-management-template-config/* /opt/seamless/conf/dealer-management-system/templates/

#sed -i "s+/var/seamless/log/dealer-management-system/+/var/seamless/log/dealer-management-system/${name}/+g" /opt/seamless/conf/dealer-management-system/log4j.properties
sed -i "s+/var/seamless/log/dealer-management-system+/var/seamless/log/dealer-management-system/${name}+g" /opt/seamless/conf/dealer-management-system/log4j2.xml
