---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ers-standard-link-log 
  namespace: ers-prod
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: nfs.storage-class/nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage-class
