apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-batch-scheduling
  namespace: ers-prod
  labels:
    app: batch-scheduling
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: batch-scheduling
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"        
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.68.82/32 
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"        
#        sidecar.istio.io/inject: "true"
      labels:
        app: batch-scheduling
        version: v1
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      initContainers:
        - name: copy-configs
          image: sdsdockerhub/ubuntu:latest
          #resources:
          #  limits:
          #    cpu: '200m'
          #    memory: 200Mi
          #  requests:
          #    cpu: 100m              
          #    memory: 100Mi                                         
          command: ['bash','/scripts/copy-bss-configs']
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /ers-common-config
              name: vol-common-conf
            - mountPath: /bss-config
              name: vol-conf
            - mountPath: /bss-config-templates
              name: vol-conf-template
            - mountPath: /bss-config-samplecsv
              name: vol-conf-samplecsv               
            - mountPath: /bss-config-datafed-template
              name: vol-conf-datafed-template
            - mountPath: /scripts
              name: copy-bss-configs
            - mountPath: /bss-notifications
              name: vol-conf-notifications  
      containers:
      - name: ers-batch-scheduling
        image: sdsdockerhub/batch-scheduling-system:feature-GPB-1081-3
        #image: sdsdockerhub/batch-scheduling-system:feature-SE-435-5
        imagePullPolicy: IfNotPresent
        env:
        #- name: JAVA_TOOL_OPTIONS
        #  value: "-Xms200M -Xmx200M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=1"
        - name: DEFAULT_TIME_ZONE
          value: "Asia/Dhaka"
        - name: TZ
          value: "Asia/Dhaka"          
        #resources:
        #  limits:
        #    cpu: '1000m'
        #    memory: 200Mi
        #  requests:
        #    cpu: 500m
        #    memory: 500Mi
       # readinessProbe:
       #   exec:
       #     command:
       #     - telnet
       #     - 127.0.0.1
       #     - "8085"
       #   initialDelaySeconds: 60
       #   periodSeconds: 5
       # livenessProbe:
       #   exec:
       #     command:
       #     - telnet
       #     - 127.0.0.1
       #     - "8085"
       #   initialDelaySeconds: 60
       #   periodSeconds: 5
        ports:
          - containerPort: 8085
        #dnsPolicy: Default
        volumeMounts:
          - mountPath: /opt/seamless/conf
            name: ers-config-path
          - mountPath: /var/seamless/spool/tdr 
            name: tdr-report-pvc
          - mountPath: /var/seamless/log/batch-scheduling
            name: vol-log
          - mountPath: /usr/share/zoneinfo/Asia/Dhaka
            name: tz-dhaka
            subPath: Dhaka            
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka              
        - name: vol-log #PVC
#         emptyDir: {}
          persistentVolumeClaim:
            claimName: batch-scheduling-log
        - name: tdr-report-pvc #PVC
#         emptyDir: {}
          persistentVolumeClaim:
            claimName: bi-tdr-reports
        - name: ers-config-path             #BASE PATH
          emptyDir: {}                  
        - name: vol-common-conf             #COMMON CONFIG
          configMap:
            name: ers-common-config
        - name: vol-conf                    #Config
          configMap:
            name: bss-config
        - name: vol-conf-template           #Templates
          configMap:
            name: bss-config-templates
        - name: vol-conf-datafed-template   #DataFeeder Template
          configMap:
            name: bss-datafeeder-template
        - name: vol-conf-samplecsv          #SampleCsv
          configMap:
            name: bss-samplecsv            
        - name: copy-bss-configs            #Copying Script
          configMap:
            name: copy-bss-configs
        - name: vol-conf-notifications      #Notifications  
          configMap:
            name: bss-notifications
      imagePullSecrets:
        - name: private-repo
