apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-from-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage-class
  resources:
    requests:
      storage: 100m
