apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ers-txe
  namespace: ers-prod
  labels:
    app: ers-txe
    version: v1
spec:
  podManagementPolicy: Parallel
  replicas: 1
  serviceName: ers-txe-service
  serviceName: ers-txe-service-8088
  selector:
    matchLabels:
      app: ers-txe
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.72.46/32,10.18.72.42/32,10.18.72.45/32
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        sidecar.istio.io/inject: "true"
      labels:
        app: ers-txe
        version: v1
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
#     affinity:
#       podAntiAffinity:
#         requiredDuringSchedulingIgnoredDuringExecution:
#         - labelSelector:
#             matchExpressions:
#             - key: app
#               operator: In
#               values:
#               - ers-txe
#           topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: copy-configs
          image: sdsdockerhub/ubuntu:latest
          env:
          - name: HOSTNAME_COMMAND
            valueFrom:
              fieldRef: {fieldPath: metadata.name}
#          resources:
#            limits:
#              cpu: '200m'
#              memory: 200Mi
#            requests:
#              cpu: 100m
#              memory: 100Mi
          command: ['bash','/scripts/copy-txe-configs']
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /var/lib/mariadb-custom/ 
              name: mysql-persistent-storage 
            - mountPath: /var/seamless/log/txe 
              name: vol-log 
            - mountPath: /etc/mysql/conf.d/ 
              name: empty-path-conf
            - mountPath: /ers-common-config
              name: vol-common-conf              
            - mountPath: /txe
              name: vol-conf
            - mountPath: /actions
              name: vol-conf-actions
            - mountPath: /pricing
              name: vol-conf-pricing
            - mountPath: /rules
              name: vol-conf-rules
            - mountPath: /minimum
              name: vol-conf-samples
            - mountPath: /templates                                    
              name: vol-conf-templates
            - mountPath: /scripts                                    
              name: vol-script 
      containers:       
      #1st Container
        - image: sdsdockerhub/mariadb-v2:10.4.17
        #- image: sdsdockerhub/mariadb-v1:10.4.17
          name: mariadb
          securityContext:
            #runAsUser: 0
            privileged: true
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: refill
          - name: MYSQL_DATABASE
            value: transactionlog
          - name: HOSTNAME_COMMAND
            valueFrom:
              fieldRef: {fieldPath: metadata.name}
          - name: TZ
            value: "Asia/Dhaka"	      
 #         resources:
 #           limits:
 #             cpu: '2'
 #             memory: 200Mi
 #           requests:
 #             cpu: '1'
 #             memory: 200Mi
#          readinessProbe:
#            tcpSocket:
#              port: 3306
#            initialDelaySeconds: 30
#            periodSeconds: 5
#          livenessProbe:
#            tcpSocket:
#              port: 3306
#            initialDelaySeconds: 30
#            periodSeconds: 5
          ports:
          - containerPort: 3306
          volumeMounts:
          - name: mysql-persistent-storage 
            mountPath: /var/lib/mariadb-custom/
          - name: empty-path-conf 
            mountPath: /etc/mysql/conf.d/ 
          - name: txlog-schema
            mountPath: /docker-entrypoint-initdb.d
          - mountPath: /usr/share/zoneinfo/Asia/Dhaka
            name: tz-dhaka
            subPath: Dhaka	    
        #2nd Container    
        - name: ers-txe
          image: sdsdockerhub/ers-txe:feature-GPB-1204-4
          #image: sdsdockerhub/ers-txe:feature-GPB-1201-33
          #image: sdsdockerhub/ers-txe:feature-GPB-1092-13
          imagePullPolicy: IfNotPresent
          env:
  #        - name: JAVA_TOOL_OPTIONS
   #         value: " -Xms200M -Xmx25000M -XX:PermSize=512m -XX:+UseG1GC  -XX:InitiatingHeapOccupancyPercent=70  -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=10 -Dlogging.config=/opt/seamless/conf/txe/log4j2.xml"
          - name: DEFAULT_TIME_ZONE
            value: "Asia/Dhaka"
          - name: TZ
            value: "Asia/Dhaka"
          - name: HOSTNAME_COMMAND
            valueFrom:
              fieldRef: {fieldPath: metadata.name}
    #      resources:
     #       limits:
     #         cpu: '10'
     #         memory: 2200Mi
     #       requests:
     #         cpu: '8'
     #         memory: 2200Mi
  #        readinessProbe:
  #          tcpSocket:
  #            port: 8088
  #          initialDelaySeconds: 30
  #          periodSeconds: 5
  #        livenessProbe:
  #          tcpSocket:
  #            port: 8088
  #          initialDelaySeconds: 30
  #          periodSeconds: 5
          ports:
            - containerPort: 8777
            - containerPort: 8088
#           - containerPort: 48077
          #dnsPolicy: Default
          volumeMounts:
            - mountPath: /opt/seamless/conf/
              name: ers-config-path 
            - mountPath: /var/seamless/log/txe
              name: vol-log
            - mountPath: /usr/share/zoneinfo/Asia/Dhaka
              name: tz-dhaka
              subPath: Dhaka              
        #3nd Container    
        - name: txe-filebeat 
          image: sdsdockerhub/filebeat:8.1.0 
          args: [
            "-c", "/usr/share/filebeat/custom/filebeat.yml",
#           "--path.data", "/usr/share/filebeat/txe-registry/$(HOSTNAME_COMMAND)/txe-data",
          ]
          env:
          - name: TZ
            value: "Asia/Dhaka"
          - name: HOSTNAME_COMMAND
            valueFrom:
              fieldRef: {fieldPath: metadata.name}
      #    resources:
      #      limits:
      #        cpu: '150m'
      #        memory: 200Mi
      #      requests:
      #        cpu: '50m'
      #        memory: 200Mi
          ports:
          volumeMounts:
          - name: vol-log 
            mountPath: /var/seamless/log/txe
          - name: filebeat-config
            mountPath: /usr/share/filebeat/custom/
          - name: filebeat-registry
            mountPath: /usr/share/filebeat/txe-registry
          - mountPath: /usr/share/zoneinfo/Asia/Dhaka
            name: tz-dhaka
            subPath: Dhaka
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka              
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: txe-config
        - name: vol-conf-templates
          configMap:
            name: txe-config-templates
        - name: vol-conf-rules
          configMap:
            name: txe-config-rules
        - name: vol-conf-actions
          configMap:
            name: txe-config-actions
        - name: vol-conf-pricing
          configMap:
            name: txe-config-pricing
        - name: vol-conf-samples
          configMap:
            name: txe-config-samples
        - name: vol-script
          configMap:
            name: copy-script
        - name: vol-log
          persistentVolumeClaim:
            claimName: txe-log
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-txe-pvc
        - name: txlog-schema 
          configMap:
            name: txe-config-mysql
        - name: filebeat-config
          configMap:
            name: gp-filebeat-configmap-txlog            
        - name: filebeat-registry
          persistentVolumeClaim:
            claimName: filebeat-registry-txlog            
        - name: ers-config-path
          emptyDir: {} 
        - name: empty-path-custom
          emptyDir: {} 
        - name: empty-path-conf
          emptyDir: {} 
      imagePullSecrets:
        - name: private-repo
