apiVersion: batch/v1
kind: CronJob
metadata:
  name: ers-perf-nm-reportdownload-24hrs
spec:
  suspend : true        
  schedule: "00 18 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: seamless-one-perf
            image: default-route-openshift-image-registry.apps.pocpbm-nexp.grameenphone.com/openshift/gp_reportdownload_lt:v1 
            imagePullPolicy: Always
            command: ['sh','-c','/home/locust/scripts/run.sh']
            env:
            - name: SERVER_FQDN
              value: "http://nginx-service.ers-prod.svc.cluster.local:18080"
            - name: USER_COUNT
              value: "1"
            - name: SPAWN_RATE
              value: "1"
            - name: EXTRA_PARAMS
              value: "" 
            volumeMounts:
            - mountPath: /usr/share/zoneinfo/Asia/Dhaka
              name: tz-dhaka
              subPath: Dhaka
            - mountPath: /home/locust/scripts/locust.py 
              name: reportdownload-script 
              subPath: locust.py
            - mountPath: /home/locust/data/downloadC2SReport.csv 
              name: reportdownload-data 
              subPath: downloadC2SReport.csv 
          restartPolicy: OnFailure
          volumes:
          - name: tz-dhaka
            configMap:
              name: asia-dhaka-tz-config
              items:
              - key: Dhaka
                path: Dhaka
          - name: reportdownload-script 
            configMap:
              name: reportdownload-script 
          - name: reportdownload-data 
            configMap:
              name: reportdownload-data
