apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ers-identity-management
  namespace: ers-prod
  labels:
    app: ers-identity-management
    version: v1
spec:
  podManagementPolicy: Parallel
  replicas: 1
  serviceName: ers-identity-management-service
  strategy:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      # maxSurge:  40%
       #MaxUnavailable: 20%
      partition: 1
  selector:
    matchLabels:
      app: ers-identity-management
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.68.82/32
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
#        sidecar.istio.io/inject: "true"
      labels:
        app: ers-identity-management
        version: v1
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      initContainers:
        - name: copy-configs
          image: sdsdockerhub/ubuntu:latest
          env:
          - name: HOSTNAME_COMMAND
            valueFrom:
              fieldRef: {fieldPath: metadata.name}
         # resources:
         #   limits:
         #     cpu: '200m'
         #     memory: 200Mi
         #   requests:
         #     cpu: 100m              
         #     memory: 100Mi                               
          command: ['bash','/scripts/copy-identity-management-configs']
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /ers-common-config
              name: vol-common-conf
            - mountPath: /identity-management-config
              name: vol-conf
            - mountPath: /identity-management-templates-config
              name: vol-templates-conf
            - mountPath: /scripts
              name: copy-identity-management-configs
      containers:
      - name: ers-identity-management
        image: sdsdockerhub/ers-identity-management:feature-GPB-1104-2
        #image: sdsdockerhub/ers-identity-management:feature-GPB-1092-4
        imagePullPolicy: Always 
       # resources:
        #  limits:
        #    cpu: '2500m'
        #    memory: 200Mi
        #  requests:
        #    cpu: '200m'              
        #    memory: '500m'                      
        env:
        #- name: JAVA_TOOL_OPTIONS
        #  value: "-Xms200M -Xmx200M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=3"
        - name: DEFAULT_TIME_ZONE
          value: "Asia/Dhaka" 
        - name: TZ
          value: "Asia/Dhaka"
        ports:
          - containerPort: 8219  
#         - containerPort: 48077  
        #dnsPolicy: Default
        readinessProbe:
          tcpSocket:
            port: 8219
          initialDelaySeconds: 30
          periodSeconds: 5  
        livenessProbe:
          tcpSocket:
            port: 8219
          initialDelaySeconds: 30
          periodSeconds: 5                   
        volumeMounts:
          - mountPath: /opt/seamless/conf
            name: ers-config-path
          - mountPath: /var/seamless/log/identity-management
            name: vol-log                                    
          - mountPath: /usr/share/zoneinfo/Asia/Dhaka
            name: tz-dhaka
            subPath: Dhaka            
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka              
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: identity-management-config
        - name: vol-templates-conf
          configMap:
            name: identity-management-templates-config
        - name: vol-log
          persistentVolumeClaim:
            claimName: ers-identity-management-log
        - name: copy-identity-management-configs
          configMap:
            name: copy-identity-management-configs
        - name: ers-config-path
          emptyDir: {}
      imagePullSecrets:
        - name: private-repo
