apiVersion: v1
kind: ConfigMap
metadata:
  name: gp-filebeat-configmap-txlog
  namespace: ers-prod
data:
  filebeat.yml: |
    filebeat.registry.path: "/usr/share/filebeat/txe-registry/${HOSTNAME_COMMAND}/"
    filebeat.inputs:
    - type: filestream
      id: "transactionlog-${HOSTNAME_COMMAND}"
      paths:
        - "/var/seamless/log/txe/${HOSTNAME_COMMAND}/transactions.log"
      tags: ["transactionlog"]
      fields:
        logtype: "transactionlog"
      ignore_older: 18h
      clean_inactive: 2h
      close_inactive: 2h
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    logging.level: info
    logging.to_files: true
    logging.selectors: [ harvester, input ]
    logging.files:
      rotateeverybytes: 5000000
      path: /usr/share/filebeat/logs
      name: filebeat.log
      keepfiles: 5
    output.logstash:
      hosts: ["gp-logstash-txlog:9030"]
      loadbalance: true
      bulk_max_size: 1024
      worker: 32
      compression_level: 1
    queue.mem:
      events: 32768
      flush.min_events: 1
      flush.timeout: 3s
