apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-uciplink-sim
  namespace: ers-prod
  labels:
    app: ers-uciplink
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: ers-uciplink
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.72.46/32,10.18.72.42/32,10.18.72.45/32
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        sidecar.istio.io/inject: "true"
      labels:
        app: ers-uciplink
        version: v1
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      initContainers:
        - name: copy-configs
          image: sdsdockerhub/ubuntu:latest
          env:
          - name: POD_NAME 
            valueFrom:
              fieldRef: {fieldPath: metadata.name}
#         resources:
#           limits:
#             cpu: '200m'
#             memory: 200Mi
#           requests:
#             cpu: '100m'
#             memory: 100Mi
          command: ['bash','/scripts/copy-uciplink-config']
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /ers-common-config
              name: vol-common-conf
            - mountPath: /ucip-config
              name: vol-conf
            - mountPath: /scripts
              name: copy-uciplink-config       
      containers:
        - name: ers-uciplink
          image: sdsdockerhub/ers-uciplink:feature-GPB-912-5
          #image: sdsdockerhub/ers-uciplink:1.49.1
          imagePullPolicy: IfNotPresent
#         resources:
#           limits:
#             cpu: '750m'
#             memory: 200Mi
#           requests:
#             cpu: '500m'
#             memory: 1500Mi
          readinessProbe:
            tcpSocket:
              port: 8010
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8010
            initialDelaySeconds: 30
            periodSeconds: 20
          env:
          - name: JAVA_TOOL_OPTIONS
            value: "-Xms200M -Xmx200M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=1"
          - name: DEFAULT_TIME_ZONE
            value: "Asia/Dhaka" 
          - name: TZ
            value: "Asia/Dhaka"        
          ports:
            - containerPort: 8010
#           - containerPort: 48010                        
          #dnsPolicy: Default
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path           
            - mountPath: /var/seamless/log/uciplink
              name: vol-log
            - mountPath: /usr/share/zoneinfo/Asia/Dhaka
              name: tz-dhaka
              subPath: Dhaka              
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka              
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: uciplink-config
        - name: vol-log
          persistentVolumeClaim:
            claimName: uciplink-log
        - name: ers-config-path
          emptyDir: {}    
        - name: copy-uciplink-config 
          configMap:
            name: copy-uciplink-config                 
      imagePullSecrets:
        - name: private-repo
