apiVersion: v1
kind: ConfigMap
metadata:
  name: gp-filebeat-configmap-lang-pref
  namespace: ers-prod
data:
  filebeat.yml: |
    filebeat.registry.path: /usr/share/filebeat/registry/
    filebeat.inputs:
    - type: log
      id: lang-pref
      paths:
        - "/var/seamless/log/notification-language-preference/source/daily_reference_*.csv"
        - "/var/seamless/log/notification-language-preference/source/weekly_reference_*.csv"
      tags: ["lang-pref"]
      fields:
        logtype: "lang-pref"
      clean_inactive: 24h
      ignore_older: 8h
      close_inactive: 8h
      exclude_files: ['\.gz$']      
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    logging.level: info
    logging.to_files: true
    logging.selectors: [ harvester, input ]
    logging.files:
      rotateeverybytes: 5000000
      path: /usr/share/filebeat/logs
      name: filebeat.log
      keepfiles: 5
    output.logstash:
      hosts: ["gp-logstash-others:9033"]
      loadbalance: true
      bulk_max_size: 1
      worker: 1
      compression_level: 1
    queue.mem:
      events: 32
      flush.min_events: 1
      flush.timeout: 1s
