#!/bin/bash
name=`echo ${POD_NAME} | rev |cut -d'-' -f1 | rev `
mkdir -p /opt/seamless/conf/region-management-core 
mkdir -p /opt/seamless/conf/region-management-core/templates

cp /ers-common-config/* /opt/seamless/conf/
cp /region-management-config/* /opt/seamless/conf/region-management-core 
cp /region-management-templates-config/* /opt/seamless/conf/region-management-core/templates 

sed -i "s+/var/seamless/log/region-management-core/+/var/seamless/log/region-management-core/${name}/+g" /opt/seamless/conf/region-management-core/log4j.properties
sed -i "s+/var/seamless/log/region-management-core/+/var/seamless/log/region-management-core/${name}/+g" /opt/seamless/conf/region-management-core/log4j2.properties
