apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-product-management
  namespace: ers-prod
  labels:
    app: ers-product-management
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: ers-product-management
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.72.46/32,10.18.72.42/32,10.18.72.45/32
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        sidecar.istio.io/inject: "true"
      labels:
        app: ers-product-management
        version: v1
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      initContainers:
        - name: copy-configs
          image: sdsdockerhub/ubuntu:latest
          env:
          - name: POD_NAME 
            valueFrom:
              fieldRef: {fieldPath: metadata.name}          
          #resources:
          #  limits:
          #    cpu: '200m'
          #    memory: 200Mi
          #  requests:
          #    cpu: 100m              
          #    memory: 100Mi                                         
          command: ['bash','/scripts/copy-product-management-configs']
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /ers-common-config
              name: vol-common-conf
            - mountPath: /product-management-config
              name: vol-conf
            - mountPath: /product-management-template-config
              name: vol-conf-template
            - mountPath: /scripts
              name: copy-product-management-configs
      containers:
        - name: ers-product-management
          image: sdsdockerhub/product-management-system:feature-GPB-1081-6
          #image: sdsdockerhub/product-management-system:feature-GPB-912-1
          imagePullPolicy: IfNotPresent
          env:
          #- name: JAVA_TOOL_OPTIONS
          #  value: "-Xms200M -Xmx200M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=3"
          - name: DEFAULT_TIME_ZONE
            value: "Asia/Dhaka"
          - name: TZ
            value: "Asia/Dhaka"
          #resources:
          #  limits:
          #    cpu: '500m'
          #    memory: 200Mi
          #  requests:
          #    cpu: '250m'
          #    memory: 200Mi
          readinessProbe:
            tcpSocket:
              port: 8012
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8012
            initialDelaySeconds: 30
            periodSeconds: 20
          ports:
            - containerPort: 8012
          #dnsPolicy: Default
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /var/seamless/log/product-management
              name: vol-log
            - mountPath: /usr/share/zoneinfo/Asia/Dhaka
              name: tz-dhaka
              subPath: Dhaka              
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka              
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: product-management-config
        - name: vol-conf-template
          configMap:
            name: product-management-templates
        - name: copy-product-management-configs
          configMap:
            name: copy-product-management-configs
        - name: vol-log
          persistentVolumeClaim:
            claimName: product-management-log
        - name: ers-config-path
          emptyDir: {}
      imagePullSecrets:
        - name: private-repo
