apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-businesslogic
  namespace: ers-prod
  labels:
    app: ers-businesslogic
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: ers-businesslogic
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.72.46/32,10.18.72.42/32,10.18.72.45/32
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"        
#        sidecar.istio.io/inject: "true"
      labels:
        app: ers-businesslogic
        version: v1
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      initContainers:
        - name: copy-configs
          image: sdsdockerhub/ubuntu:latest
          env:
          - name: POD_NAME 
            valueFrom:
              fieldRef: {fieldPath: metadata.name}
         # resources:
         #   limits:
         #     cpu: '200m'
         #     memory: 200Mi
         #   requests:
         #     cpu: '100m'
         #     memory: 100Mi
          command: ['bash','/scripts/copy-business-configs']
          volumeMounts:
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /ers-common-config
              name: vol-common-conf
            - mountPath: /businesslogic
              name: vol-conf
            - mountPath: /scripts
              name: copy-business-configs    
      containers:
        - name: ers-businesslogic
          image: sdsdockerhub/ers-businesslogic:feature-GPB-912-13
          #image: sdsdockerhub/ers-businesslogic:3.55.0
          imagePullPolicy: IfNotPresent
        #  resources:
        #    limits:
        #      cpu: '500m'
        #      memory: 200Mi
        #    requests:
        #      cpu: '100m'
        #      memory: 200Mi
          readinessProbe:
            tcpSocket:
              port: 8922
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8922
            initialDelaySeconds: 30
            periodSeconds: 20
          env:
         # - name: JAVA_TOOL_OPTIONS
         #   value: "-Xms200M -Xmx200M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=1"
          - name: DEFAULT_TIME_ZONE
            value: "Asia/Dhaka"
          - name: TZ
            value: "Asia/Dhaka"
          ports:
            - containerPort: 8922
          #dnsPolicy: Default  
          volumeMounts:
            - mountPath: /var/seamless/log/businesslogic
              name: vol-log
            - mountPath: /opt/seamless/conf
              name: ers-config-path
            - mountPath: /usr/share/zoneinfo/Asia/Dhaka
              name: tz-dhaka
              subPath: Dhaka                              
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka              
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: businesslogic-config
        - name: vol-log
          persistentVolumeClaim:
            claimName: businesslogic-log
        - name: copy-business-configs
          configMap:
            name: copy-business-configs
        - name: ers-config-path
          emptyDir: {}     
      imagePullSecrets:
        - name: private-repo                
