#!/bin/bash

mkdir -p /opt/seamless/conf/identity-management
mkdir -p /opt/seamless/conf/identity-management/templates

cp /ers-common-config/* /opt/seamless/conf/
cp /identity-management-config/* /opt/seamless/conf/identity-management/
cp /identity-management-templates-config/* /opt/seamless/conf/identity-management/templates/


value=`echo ${HOSTNAME_COMMAND} | rev | cut -d '-' -f1|rev`
value=`printf -v value "%02d" $value; echo $value`
sed -i "s+reference_generator.node_id=02+reference_generator.node_id=${value}+g" /opt/seamless/conf/identity-management/identity-management.properties

#sed -i  "s+/var/seamless/log/identity-management/+/var/seamless/log/identity-management/idms-${value}/+g" /opt/seamless/conf/identity-management/log4j.properties
sed -i  "s+/var/seamless/log/identity-management+/var/seamless/log/identity-management/idms-${value}+g" /opt/seamless/conf/identity-management/log4j2.xml

