FROM default-route-openshift-image-registry.apps.pocpbm-nexp.grameenphone.com/openshift/seamless-one-performance:POST-LIVE-LT-V1
COPY c2s_Rc_ExGt.csv /opt/seamless/conf/seamless-one-performance/data/GP/.
