---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-account-management
  name: ers-account-management-service
spec:
  ports:
    - name: http-ers-account-management
      port: 8092
      targetPort: 8092
  selector:
    app: ers-account-management
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-account-management-dms
  name: ers-account-management-service-dms
spec:
  ports:
    - name: http-ers-account-management-dms
      port: 8092
      targetPort: 8092
  selector:
    app: ers-account-management-dms
  type: ClusterIP

