---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-access-management-system
  name: ers-access-management-system-service
spec:
  ports:
    - name: http-ers-access-management-system
      port: 8374
      targetPort: 8374
  selector:
    app: ers-access-management-system
  type: ClusterIP
