---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-bi-tdr
  name: ers-bi-tdr-service
spec:
  ports:
    - name: http-ers-bi-tdr
      port: 8917
      targetPort: 8917
  selector:
    app: ers-bi-tdr
  type: ClusterIP
