---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-bi-aggregator
  name: ers-bi-aggregator-service
spec:
  ports:
    - name: http-ers-bi-aggregator
      port: 8999
      targetPort: 8999
  selector:
    app: ers-bi-aggregator
  type: ClusterIP

