---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-contract-management-system
  name: ers-contract-management-system-service
spec:
  ports:
    - name: http-ers-contract-management-system-service
      port: 38082
      targetPort: 38082
  selector:
    app: ers-contract-management-system
  type: ClusterIP
