---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-coreproxy
  name: ers-coreproxy-service
spec:
  ports:
    - name: http-ers-coreproxy-service
      port: 8912
      targetPort: 8912
  selector:
    app: ers-coreproxy
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-coreproxy
  name: ers-coreproxy-service-8983
spec:
  ports:
    - name: http-ers-coreproxy-service-8983
      port: 8983
      targetPort: 8983
  selector:
    app: ers-coreproxy
  type: ClusterIP

