---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: dealer-management-system
  name: ers-dealer-management-system-service
spec:
  ports:
    - name: http-dealer-management-system
      port: 8033
      targetPort: 8033
  selector:
    app: dealer-management-system
  type: ClusterIP

