---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-commission-engine
  name: ers-commission-engine-svc
spec:
  ports:
    - name: http-commission-engine-svc
      port: 8094
      targetPort: 8094
  selector:
    app: ers-commission-engine 
  type: ClusterIP

