---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-standard-link 
  name: ers-standard-link-service 
spec:
  ports:
    - name: http-ers-standard-link-service
      port: 8098
      targetPort: 8098
  selector:
    app: ers-standard-link 
  type: ClusterIP
