---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-identity-management
  name: ers-identity-management-service
spec:
  ports:
    - name: http-ers-identity-management
      port: 8219
      targetPort: 8219
  selector:
    app: ers-identity-management
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-identity-management-new
  name: ers-identity-management-service-new
spec:
  ports:
    - name: http-ers-identity-management
      port: 8219
      targetPort: 8219
  selector:
    app: ers-identity-management-new
  type: ClusterIP


