---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ims-bridge
  name: ims-bridge-service
spec:
  ports:
    - name: http-ims-bridge
      port: 8919
      targetPort: 8919
  selector:
    app: ims-bridge
  type: ClusterIP

