---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-nginx
  name: nginx-service
spec:
  ports:
    - name: http-nginx
      port: 18080
      targetPort: 18080
      nodePort: 30080
  selector:
    app: ers-nginx
  type: NodePort

