---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-notification-ui 
  name: ers-notification-ui-service
spec:
  ports:
    - name: http-ers-notification-ui-service
      port: 8177
      targetPort: 8177
  selector:
    app: ers-notification-ui 
  type: ClusterIP

