---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-object-store-manager 
  name: ers-object-store-service
spec:
  ports:
    - name: http-ers-object-store-service
      port: 3000
      targetPort: 3000
  selector:
    app: ers-object-store-manager 
  type: ClusterIP

