---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-region-management
  name: ers-region-management-service
  namespace: ers-prod
spec:
  ports:
    - name: http-ers-region-management-service
      port: 8000
      targetPort: 8000
  selector:
    app: ers-region-management
  type: ClusterIP

