---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-subscribersystem
  name: ers-subscribersystem-service
spec:
  ports:
    - name: http-ers-subscribersystem
      port: 8087
      targetPort: 8087
  selector:
    app: ers-subscribersystem
  type: ClusterIP

