---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-template-management-system
  name: ers-template-management-system-service
spec:
  ports:
    - name: http-ers-template-management-system
      port: 8378
      targetPort: 8378
  selector:
    app: ers-template-management-system
  type: ClusterIP

