---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-txe-proxy
  name: ers-txe-proxy-service
spec:
  ports:
    - name: http-txe-proxy
      port: 38777
      targetPort: 38777
  selector:
    app: ers-txe-proxy
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: ers-prod
  labels:
    app: ers-txe-proxy-jfr
  name: ers-txe-proxy-service-jfr
spec:
  ports:
    - name: http-txe-proxy
      port: 38777
      targetPort: 38777
  selector:
    app: ers-txe-proxy-jfr
  type: ClusterIP

