apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-bimail
  namespace: ers-prod
  labels:
    app: ers-bimail
    version: v1
spec:
  replicas: 1 
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: ers-bimail
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.72.46/32,10.18.72.42/32,10.18.72.45/32
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        sidecar.istio.io/inject: "true"
      labels:
        app: ers-bimail
        version: v1
    spec:
      #serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      initContainers:
        - name: copy-configs
          image: sdsdockerhub/ubuntu:latest
          #resources:
          #  limits:
          #    cpu: '200m'
          #    memory: 200Mi
          #  requests:
          #    cpu: '100m'              
          #    memory: 100Mi                                         
          command: ["bash","-c"]
          args: [ "  cd /opt/seamless/conf/bi-mail-engine && tar -xf conf.tar --no-overwrite-dir && tar -xf mail.tar --no-overwrite-dir "]          
          volumeMounts:
            - mountPath: /opt/seamless/conf/bi-mail-engine
              name: ers-empty-dir
            - mountPath: /opt/seamless/conf/bi-mail-engine/conf.tar
              name: vol-conf
              subPath: conf.tar
            - mountPath: /opt/seamless/conf/bi-mail-engine/mail.tar
              name: vol-mail
              subPath: mail.tar                            
      containers:
      - name: ers-bimail
        image: sdsdockerhub/bi-mail-engine:GPB-729-2
        #command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        imagePullPolicy: IfNotPresent
       # resources:
       #   limits:
       #     cpu: '1000m'
       #     memory: 200Mi
       #   requests:
       #     cpu: 500m              
       #     memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 8918
          initialDelaySeconds: 90
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8918
          initialDelaySeconds: 90
          periodSeconds: 20
        env:
        #- name: JAVA_TOOL_OPTIONS
        #  value: "-Xms200M -Xmx200M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=1"
        - name: DEFAULT_TIME_ZONE
          value: "Asia/Dhaka" 
        - name: TZ
          value: "Asia/Dhaka"                     
        ports:
          - containerPort: 8918
        #dnsPolicy: Default
        volumeMounts:
          - mountPath: /opt/seamless/conf
            name: vol-common-conf
          - mountPath: /opt/seamless/conf/bi-mail-engine
            name: ers-empty-dir
          - mountPath: /var/seamless/log/bi-mail-engine
            name: vol-log
          - mountPath: /usr/share/zoneinfo/Asia/Dhaka
            name: tz-dhaka
            subPath: Dhaka            
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka              
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: ers-bimail-config          
        - name: vol-mail
          configMap:
            name: ers-bimail-mail
        - name: vol-bimail-conf
          configMap:
            name: ers-bimail-conf
        - name: vol-log
          persistentVolumeClaim:
            claimName: ers-bimail-log
        - name: ers-empty-dir
          emptyDir: {}  
      imagePullSecrets:
        - name: private-repo        
