apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-bi-engine
  namespace: ers-prod
  labels:
    app: ers-bi-engine
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: ers-bi-engine
      version: v1
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPULimit: 100m
#        sidecar.istio.io/proxyMemoryLimit: 200Mi
#        sidecar.istio.io/proxyCPU: 50m
#        sidecar.istio.io/proxyMemory: 128Mi
#        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.18.68.82/32 
#        status.sidecar.istio.io/port: "0"
#        traffic.sidecar.istio.io/excludeInboundPorts: "0"
#        sidecar.istio.io/inject: "true"
      labels:
        app: ers-bi-engine
        version: v1
    spec:
      serviceAccountName: ers-prod-app-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        seLinuxOptions:
          type: "spc_t"
      dnsConfig:
        options:
          - name: ndots
            value: "4"
      hostAliases:
      - ip: "10.10.4.193"
#      - ip: "10.18.13.16"
        hostnames:
        - "prod-es-server.grameenphone.com"            
      containers:
      - name: ers-bi-engine
        image: sdsdockerhub/bi-engine:feature-SE-435-36
        #image: sdsdockerhub/bi-engine:feature-SE-435-34
        #image: sdsdockerhub/bi-engine:feature-SE-435-31
        imagePullPolicy: IfNotPresent
        #resources:
        #  limits:
        #    cpu: '2000m'
        #    memory: 1200Mi
        #  requests:
        #    cpu: 2000m
        #    memory: 1200Mi
        readinessProbe:
          tcpSocket:
            port: 8917
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8917
          initialDelaySeconds: 30
          periodSeconds: 20
        env:
        #- name: JAVA_TOOL_OPTIONS
        #  value: "-Xms200M -Xmx16000M -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=2" 
        - name: DEFAULT_TIME_ZONE
          value: "Asia/Dhaka" 
        - name: TZ
          value: "Asia/Dhaka"                     
        ports:
          - containerPort: 8917
        #dnsPolicy: Default
        volumeMounts:
          - mountPath: /opt/seamless/conf/bi-engine
            name: vol-conf
          - mountPath: /opt/seamless/conf/bi-engine/scripts
            name: vol-scripts
          - mountPath: /var/seamless/log/bi-engine
            name: vol-log
          - mountPath: /opt/seamless/www/webapps/analytics/file/ 
            name: vol-report
          - mountPath: /opt/seamless/conf
            name: vol-common-conf
          - mountPath: /usr/share/zoneinfo/Asia/Dhaka
            name: tz-dhaka
            subPath: Dhaka            
      volumes:
        - name: tz-dhaka
          configMap:
            name: asia-dhaka-tz-config
            items:
            - key: Dhaka
              path: Dhaka              
        - name: vol-common-conf
          configMap:
            name: ers-common-config
        - name: vol-conf
          configMap:
            name: bi-engine-config
        - name: vol-scripts
          configMap:
            name: bi-engine-scripts 
        - name: vol-log
#         emptyDir: {}
          persistentVolumeClaim:
            claimName: bi-engine-new-log 
        - name: vol-report
#         emptyDir: {}
          persistentVolumeClaim:
            claimName: bi-engine-report 

      imagePullSecrets:
        - name: private-repo
