apiVersion: batch/v1
kind: CronJob
metadata:
  name: gp-redis-backup
spec:
  schedule: "0 * * * *"               #CRON TIME IS BASED ON GMT
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: auto-deployment-restart
          containers:
          - name: gp-redis-backup
            image: default-route-openshift-image-registry.apps.pocpbm-nexp.grameenphone.com/openshift/auto-restart:v1
            imagePullPolicy: Always
            env:
            - name: TZ
              value: "Asia/Dhaka"  
            command:
            - /bin/sh
            - -c
            - "oc exec gp-redis-0 -- redis-cli SAVE" 
            resources:
              limits:
                cpu: "50m"
                memory: "1Gi"              
              requests:
                cpu: "50m"
                memory: "1Gi"
            volumeMounts:
            - mountPath: /usr/share/zoneinfo/Asia/Dhaka
              name: tz-dhaka
              subPath: Dhaka               
          restartPolicy: OnFailure
          volumes:
          - name: tz-dhaka
            configMap:
              name: asia-dhaka-tz-config
              items:
              - key: Dhaka
                path: Dhaka          
